const slides = [
  {
    id: 1,
    author: "kvilr",
    url: `https://app.kvilr.com/wp-content/uploads/2024/04/img-2.jpg`,
    alt: "Financial Technology",
    title: "FinTech",
    desc: "Building a Financial Technology that bring in your dream revenue shouldn't be a rocket science. Let us make that happen for you in no time..",
    calltoaction: "Request for Demo",
    calltoactionlink: "/",
  },

  {
    id: 2,
    author: "kvilr",
    url: `https://app.kvilr.com/wp-content/uploads/2024/04/img-3.jpg`,
    alt: "Managed Services",
    title: "Managed Services",
    desc: "We partner with industry top providers to bring you on-demand services",
    calltoaction: "Get in touch",
    calltoactionlink: "/",
  },
  {
    id: 3,
    author: "kvilr",
    url: `https://app.kvilr.com/wp-content/uploads/2024/04/img-4.jpg`,
    alt: "Managed Services",
    title: "Managed Services",
    desc: "We partner with industry top providers to bring you on-demand services",
    calltoaction: "Get in touch",
    calltoactionlink: "/",
  },
  {
    id: 4,
    author: "kvilr",
    url: `https://app.kvilr.com/wp-content/uploads/2024/04/img-5.jpg`,
    alt: "Managed Services",
    title: "Managed Services",
    desc: "We partner with industry top providers to bring you on-demand services",
    calltoaction: "Get in touch",
    calltoactionlink: "/",
  },
  {
    id: 5,
    author: "kvilr",
    url: `https://app.kvilr.com/wp-content/uploads/2024/04/img-6.jpg`,
    alt: "Managed Services",
    title: "Managed Services",
    desc: "We partner with industry top providers to bring you on-demand services",
    calltoaction: "Get in touch",
    calltoactionlink: "/",
  },
  {
    id: 6,
    author: "kvilr",
    url: `https://app.kvilr.com/wp-content/uploads/2024/04/img-7.jpg`,
    alt: "Managed Services",
    title: "Managed Services",
    desc: "We partner with industry top providers to bring you on-demand services",
    calltoaction: "Get in touch",
    calltoactionlink: "/",
  },
  {
    id: 7,
    author: "kvilr",
    url: `https://app.kvilr.com/wp-content/uploads/2024/04/img-8.jpg`,
    alt: "Managed Services",
    title: "Managed Services",
    desc: "We partner with industry top providers to bring you on-demand services",
    calltoaction: "Get in touch",
    calltoactionlink: "/",
  },
  {
    id: 8,
    author: "kvilr",
    url: `https://app.kvilr.com/wp-content/uploads/2024/04/img-9.jpg`,
    alt: "Managed Services",
    title: "Managed Services",
    desc: "We partner with industry top providers to bring you on-demand services",
    calltoaction: "Get in touch",
    calltoactionlink: "/",
  },
  {
    id: 9,
    author: "kvilr",
    url: `https://app.kvilr.com/wp-content/uploads/2024/04/img-10.jpg`,
    alt: "Managed Services",
    title: "Managed Services",
    desc: "We partner with industry top providers to bring you on-demand services",
    calltoaction: "Get in touch",
    calltoactionlink: "/",
  },
];

export { slides };
